app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import Home, TareasView, TareaDeleteView, TareaEditarView, SingUpView, CustomLoginView


app_name = 'todo'

urlpatterns = [
    path('', Home.as_view(), name = 'home'),
    path('login/', CustomLoginView.as_view(template_name = 'login.html'), name = 'login'),
    path('register/', SingUpView.as_view(), name='register'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'login.html'), name='logout'),
    path('task/create/', TareasView.as_view(), name = 'taskcreate'),
    path('eliminar/<int:pk>', TareaDeleteView.as_view(), name= 'delete'),
    path('update/<int:pk>', TareaEditarView.as_view(), name='update'),

    ]

todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Tareas(models.Model):
    COLOR_CHOICES = [
        ('primary', 'Azul'),
        ('secondary', 'Gris'),
        ('success', 'Verde'),
        ('danger', 'Rojo'),
        ('warning', 'Amarillo'),
        ('info', 'Azul claro'),
        ('light', 'Blanco'),
        ('dark', 'Negro'),
    ]
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=205)
    descripcion = models.TextField()
    fecha_inicio = models.DateField(auto_now=True)
    fecha_limite = models.DateField()
    color = models.CharField(max_length=20, choices=COLOR_CHOICES, default='primary' )
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.titulo

todo/forms.py
from django import forms
from .models import Tareas



class TareasForm(forms.ModelForm):
   
    class Meta:
        model = Tareas
        fields = [
            'titulo',
            'descripcion',
            'fecha_limite',

        ]

todo/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Tareas
from .forms import TareasForm
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.urls import reverse, reverse_lazy

class Home(LoginRequiredMixin ,generic.TemplateView):
    template_name = 'home.html'
    context_object_name = 'tareas'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tareas'] = Tareas.objects.filter(usuario = self.request.user)
        return context

    
class TareasView(generic.CreateView):
    model = Tareas
    form_class = TareasForm
    success_url = reverse_lazy('home.html')
    template_name = 'home.html'

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('todo:home')

    
class TareaDeleteView(generic.DeleteView):
    model = Tareas
    success_url = reverse_lazy('todo:home')


class TareaEditarView(generic.UpdateView):
    model = Tareas
    success_url = reverse_lazy('todo:home')
    fields = [
        'titulo',
        'descripcion',
        'fecha_limite',
    ]

    def form_valid(self, form):
        return super().form_valid(form)
    
    def form_invalid(self,form):
        return super().form_invalid(form)
    

class CustomLoginView(LoginView):
    def form_invalid(self, form):
        messages.error(self.request, 'Credenciales no validas.')        
        return super().form_invalid(form)
    

class SingUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('todo:login')
    template_name = 'register.html'

    def form_valid(self, form):        
        response = super().form_valid(form)
        messages.success(self.request, '¡Tu cuenta ha sido creada! Por favor inicia sesión.')
        return response
            
    def form_invalid(self, form):
        response = super().form_invalid(form)
        messages.error(self.request, 'Las contraseñas no coinciden.')        
        return response

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <title>To-Do List</title>
    
</head>
<header>
    <div class="container">
    <nav class="navbar navbar-expand-lg bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand text-white" href="#" >To-Do List</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="{% url 'todo:home' %}">Home</a>
              </li>
              
            </ul>
            <ul class="navbar-nav ms-auto">
              <div class='text-end d-flex'>
                <div class="name m-2">
                  {% if user.is_authenticated %}
                              <strong>Hola {{ user.username }}</strong>
                  {%endif%}
                </div>

              </div>
              <li class="nav-item ">
              <a class="nav-link text-white " href="{% url 'todo:logout' %}">Logout</a>
            </li>
            </ul>

          </div>
        </div>
      </nav>
    </div>
</header>
<body>
    

    {% comment %} {% include 'message.html' %} {% endcomment %}
    
    {% block content %}
    
    
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="sweetalert2.all.min.js"></script>
    <script src="sweetalert2.min.js"></script>
    <link rel="stylesheet" href="sweetalert2.min.css">
    {% block js_page %}
    
    {% endblock js_page %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <h1 class='text-center m-4'>Mis ToDo's</h1>
    <div class="button-container text-center">
        
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary text-center mb-4" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Crear Tarea  <i class="bi bi-pencil"></i>
        </button>
        
    </div>

  </button>

        <div class="row">
            {% for tarea in tareas %}
            <div class="col-lg-4 col-md-12 d-flex justify-content-center">
                <div class="card m-4 text-center" style="max-width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{tarea.titulo}} <i class="bi bi-card-checklist"></i></h5>
                        <p class="card-text">{{tarea.descripcion}}</p>
                        <div class="fecha d-flex ">
                            <p class=''>Inicio: {{tarea.fecha_inicio}}</p>
                            <p>Limite: {{tarea.fecha_limite}}</p>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-center">
                        <form action="" method='POST'>
                            {% csrf_token %}
                            <button type='button' class='btn btn-primary mx-4' data-bs-toggle="modal" data-bs-target="#updateModal_{{tarea.id}}">Editar</button>
                        </form>
                        <form action="{% url 'todo:delete' tarea.id %}" method='POST' id='delete_form_{{tarea.id}}'>
                            {% csrf_token %}
                            <button type='button' class='btn btn-danger mx-4' data-bs-toggle="modal" data-bs-target="#confirmModal_{{tarea.id}}">Eliminar</button>
                        </form>
                        <div class="status-status">
                            {% if tarea.status == 'Pendiente' %}
                                <p>Status: Pendiente</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>

<!-- Modal: crear tarea-->
 
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel"><i class="bi bi-journal-bookmark"></i> Nueva Tarea:</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        
    
        <form action="{% url 'todo:taskcreate' %}" method = 'POST'>
            {% csrf_token %}
            <div class="modal-body">
                
                <div class="form-group m-3">
                    <label for="titulo">Título:</label>
                    <input type="text" class="form-control" id="titulo" name="titulo">
                </div>
                <div class="form-group m-3">
                    <label for="descripcion">Descripcion:</label>
                    <textarea class="form-control" id="descripcion" name="descripcion"></textarea>
                </div>
                <div class="form-group m-3">
                    <label for="fecha_limite">Fecha limite:</label>
                    <input type="date" class="form-control" id="fecha_limite" name="fecha_limite">
                </div>
                
                <div class="form-group m-3">
                    <input type="radio" id="status" name="fav_language" value="status">
                    <label for="status">Pendiente</label><br>

                </div>
                    
            </div>


            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              <button type="submit" class="btn btn-primary">Guardar tarea</button>
            </div>

        </form>

        
      </div>
    </div>
</div>

<!-- Modal: crear Eliminar-->

{% for tarea in tareas %}
<div class="modal fade" id="confirmModal_{{tarea.id}}" tabindex="-1" aria-labelledby="confirmModalLabel_{{tarea.id}}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmModalLabel_{{tarea.id}}">Confirmar eliminación</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Está seguro de que desea eliminar esta tarea?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal" onclick="document.getElementById('delete_form_{{tarea.id}}').submit();">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}


<!-- Modal: editar tarea-->

{% for tarea in tareas %}
 
<div class="modal fade" id="updateModal_{{tarea.id}}" tabindex="-1" aria-labelledby="exampleModalLabel{{tarea.id}}" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel"><i class="bi bi-journal-bookmark"></i> Editar Tarea:</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        
    
        <form action="{% url 'todo:update' tarea.id %}" method = 'POST'>
            {% csrf_token %}
            <div class="modal-body">
                
                <div class="form-group m-3">
                    <label for="titulo">Título:</label>
                    <input type="text" class="form-control" id="titulo" name="titulo" placeholder='{{tarea.titulo}}... (Completar todos los campos)'>
                </div>
                <div class="form-group m-3">
                    <label for="descripcion">Descripcion:</label>
                    <textarea class="form-control" id="descripcion" name="descripcion" placeholder='{{tarea.descripcion}}... (Completar todos los campos)'></textarea>
                </div>
                <div class="form-group m-3">
                    <label for="fecha_limite">Fecha limite:</label>
                    <input type="date" class="form-control" id="fecha_limite" name="fecha_limite" placeholder='{{tarea.fecha_limite}}'>
                </div>
                    
            </div>


            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              <button type="submit" class="btn btn-primary">Guardar tarea</button>
            </div>

        </form>

        
      </div>
    </div>
</div>
{% endfor %}


{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="container d-flex"> 
        <div class="row justify-content-center">
            <div class="col">
                <h1>Bienvenidos a To-Do List</h1>
                <form action="" method='POST'>
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="">Usuario:</label>
                        <input type="text" class='form-control' name='username' id='username' placeholder ='Aqui tu usuario'>
                    </div>

                    <br>
                    <div class="form-group">
                        <label for="">Contraseña:</label>
                        <input type="password" class='form-control' name='password' id='password' placeholder ='Aqui tu contraseña'>
                    </div>

                    <br>                    
                    <button class="btn btn-success" type='submit'>Acceder</button>
                    <a href="{% url 'todo:register' %}">Si no tenes usuario, registrate</a>

                </form>
            </div>
        </div>
    </div>

{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="container d-flex"> 
        <div class="row justify-content-center">
            <div class="col">
                <h1>Bienvenidos a ToDo-List</h1>
                <form action="" method = 'POST'>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">Usuario:</label>
                        {{form.username}}
                        {% comment %} <input type="text" class='form-control' name='username' id='username' placeholder ='Aqui tu usuario'> {% endcomment %}

                    </div>
                    <br>
                    <div class="form-group">
                        <label for="">Contraseña:</label>
                        {{form.password1}}
                        {% comment %} <input type="password" class='form-control' name='password' id='password' placeholder ='Aqui tu contraseña'> {% endcomment %}
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="">Repetir contraseña:</label>
                        {{form.password2}}
                        {% comment %} <input type="password" class='form-control' name='re-password' id='re-password' placeholder ='Aqui tu contraseña'> {% endcomment %}
                    </div>
                    <br>                    
                    <button class="btn btn-success" type='submit'>Acceder</button>
                    <br>               
                    
                </form>
            </div>
        </div>
    </div>

{% endblock content %}